### ISSUE TITLE
Composer support?

### ISSUE THREAD

**Issue by matt-bailey** [rsmclaren/silverstripe-blogcategories#1]
We use composer (http://getcomposer.org/doc/05-repositories.md#vcs) to control the dependencies on our projects. It would be great if your blog categories module supported composer, or was on packagist (https://packagist.org/packages/silverstripe/) :)

**Comment by rsmclaren** [comment]
Hey Matt, thanks for the suggestion. I'll add packagist support this week!

**Comment by gpmd** [comment]
No worries :) You probably know how to do it already, but I just added my first package to packagist (https://packagist.org/packages/gpmd/ss-bootstrap), so if you have any questions on how to do it let me know.

**Comment by rsmclaren** [comment]
I actually just learned (co-worked showed me the steps) about 10 minutes before I saw this comment haha. Kind of funny.

Good to know though if I have questions the community is here to help :D thanks!

**Comment by rsmclaren** [comment]
added composer support. Again, thanks for the suggestion!
