### ISSUE TITLE
Accesing "/catagory/category_name"  results in HTTP404 

### ISSUE THREAD

**Issue by Clustmart** [rsmclaren/silverstripe-blogcategories#11]
Hi Ryan,
with SS3.1, after /dev/build?flush=all, I can not access the /category URL. Please advise.
Best regards

**Comment by rsmclaren** [comment]
Hi dinResita.

I just tried it myself on a fresh SS3.1 RC install, latest blog, and latest version of my module and everything appeared to be working. Any other info you could provide me with?

**Comment by rsmclaren** [comment]
Going to close this. I've tested again on SS 3.1 stable and not having any issues.
