### ISSUE TITLE
Categories tab not showing on parent blog holder

### ISSUE THREAD

**Issue by matt-bailey** [rsmclaren/silverstripe-blogcategories#6]
Hi Ryan. I'm just testing an unrelated issue, but I've noticed that the categories tab isn't showing up on the parent blog holder in admin on my install. It does however show on the blog post page. I've attached some screen grabs below so you can see what I mean.

The site is a completely clean install and all done using composer/packagist. The SilverStripe version is 3.0.5 I think.

First I installed SilverStripe and set up the site. Then I installed the blog module and finally I installed the blogcategories module. The theme is the default one, Simple.

![Parent Blog Holder](https://f.cloud.github.com/assets/969385/234205/cf35cd00-876c-11e2-8e62-56ffcc954535.png)
![Blog Post](https://f.cloud.github.com/assets/969385/234206/cf4adcae-876c-11e2-8d29-5fb3903abca3.png)

**Comment by rsmclaren** [comment]
Hey Matt

This looks to come from some changes chillu had implemented and I merged. you have to add some new code to your _config.php to get the "BlogCategories" tab on the Blog Holder Page. Add the following to your _config.php

Config::inst()->update('BlogCategory', 'limit_to_holder', true);

Thanks for pointing out. I've updated the readme.md to reflect this change. As a side note I noticed that the BlogTree class is breaking now too. I'm away this weekend but should be able to look into and fix it on Monday.

**Comment by matt-bailey** [comment]
Thanks, that did the trick :)
