### ISSUE TITLE
Blog Categories Widget

### ISSUE THREAD

**Issue by matt-bailey** [rsmclaren/silverstripe-blogcategories#7]
Hi Ryan. I've created a blog categories widget to go with your blog categories module: https://github.com/matt-bailey/silverstripe-widget-categories.

I'm a frontend dev so I don't know if the code is the most optimised. If you happen to look at it and spot anything that could be improved let me know ;)

**Comment by rsmclaren** [comment]
Hey Matt

I added a category widget into my module. In doing so, I completely forgot that you made one as well! I worked off of the category cloud that chillu made. I never did say thanks to you for making that. I do wish I remembered yours, I probably could have worked it in and saved some time haha.

**Comment by matt-bailey** [comment]
Hey @IOTI, no worries. I haven't had time to keep on top of the SilverStripe core updates in recent months, so it's likely my little widget doesn't work anymore anyway ;)
